package com.metoly.morganize.core.model.security

import android.util.Base64
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.SecretKey

/**
 * Handles AES-256-GCM encryption and decryption of arbitrary byte data.
 * All crypto operations run on [Dispatchers.Default] to avoid blocking the main thread.
 *
 * Usage:
 * - Encrypt: provide plaintext bytes + a [SecretKey] → returns [EncryptionResult]
 * - Decrypt: provide ciphertext bytes + IV + the same [SecretKey] → returns plaintext bytes
 */
class EncryptionManager {

    companion object {
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_TAG_LENGTH = 128 // bits
    }

    /**
     * Encrypts [plaintext] using AES-256-GCM with the given [secretKey].
     * The IV is auto-generated by the Cipher and included in the result.
     */
    suspend fun encrypt(plaintext: ByteArray, secretKey: SecretKey): EncryptionResult =
        withContext(Dispatchers.Default) {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, secretKey)
            val iv = cipher.iv
            val ciphertext = cipher.doFinal(plaintext)
            EncryptionResult(
                ciphertext = ciphertext,
                iv = iv,
                salt = ByteArray(0) // salt is managed by KeyManager, not here
            )
        }

    /**
     * Decrypts [ciphertext] using AES-256-GCM with the given [secretKey] and [iv].
     */
    suspend fun decrypt(ciphertext: ByteArray, iv: ByteArray, secretKey: SecretKey): ByteArray =
        withContext(Dispatchers.Default) {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
            cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)
            cipher.doFinal(ciphertext)
        }

    // ── Convenience: String ↔ Base64 helpers ───────────────────────────

    /**
     * Encrypts a [plaintext] string, returning Base64-encoded ciphertext and IV strings.
     */
    suspend fun encryptString(
        plaintext: String,
        secretKey: SecretKey
    ): Triple<String, String, String> {
        val result = encrypt(plaintext.toByteArray(Charsets.UTF_8), secretKey)
        return Triple(
            Base64.encodeToString(result.ciphertext, Base64.NO_WRAP),
            Base64.encodeToString(result.iv, Base64.NO_WRAP),
            "" // salt placeholder — actual salt comes from KeyManager
        )
    }

    /**
     * Decrypts a Base64-encoded [ciphertextBase64] using a Base64-encoded [ivBase64] and [secretKey].
     */
    suspend fun decryptString(
        ciphertextBase64: String,
        ivBase64: String,
        secretKey: SecretKey
    ): String {
        val ciphertext = Base64.decode(ciphertextBase64, Base64.NO_WRAP)
        val iv = Base64.decode(ivBase64, Base64.NO_WRAP)
        val plainBytes = decrypt(ciphertext, iv, secretKey)
        return String(plainBytes, Charsets.UTF_8)
    }
}
